// Writes the generated API artifacts into the docs site.
//
// Run from the repo root:
//
//   pnpm run openapi:emit
//   # or: pnpm --filter @starter/server exec tsx src/api/v1/emit-openapi.ts
//
// Two files, both COMMITTED, which is the point: the docs site is a static
// build with no server to ask, and an artifact regenerated only at deploy time
// is an artifact nobody reviews. Checking them in means a route whose shape
// changed shows up in the pull request that changed it — and a test fails when
// they are stale, so "forgot to re-run it" is not a silent state.
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { buildOpenApiDocument } from "./openapi.js";
import { API_ROUTES, type ApiRoute } from "./routes-table.js";

const here = dirname(fileURLToPath(import.meta.url));
/** packages/server/src/api/v1 → repo root. */
const repoRoot = resolve(here, "../../../../..");

export const OPENAPI_JSON_PATH = resolve(repoRoot, "docs-site/static/openapi.json");
export const REFERENCE_MD_PATH = resolve(repoRoot, "docs-site/docs/api/reference.md");

/** The exact bytes of the committed spec, so a staleness check has one answer. */
export function openApiJson(): string {
  return `${JSON.stringify(buildOpenApiDocument(), null, 2)}\n`;
}

export function emitOpenApiDocument(target = OPENAPI_JSON_PATH): string {
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, openApiJson(), "utf8");
  return target;
}

/** Anything not filed under a resource heading — `/me`, the spec itself. */
const FALLBACK_GROUP = "Meta";

/**
 * The headings, in the order the page presents them.
 *
 * Prefix matching rather than a per-route label, so a route added to the table
 * lands under a heading without anybody remembering to file it. Whatever
 * matches nothing lands in Meta rather than vanishing from the page.
 */
const GROUPS: readonly { title: string; prefix: string }[] = [
  { title: "Entries", prefix: "/entries" },
  { title: "Clients", prefix: "/clients" },
  { title: "Projects", prefix: "/projects" },
  { title: "Tasks", prefix: "/tasks" },
  { title: "Tags", prefix: "/tags" },
  { title: "Reports", prefix: "/reports" },
];

function groupOf(route: ApiRoute): string {
  return (
    GROUPS.find((group) => route.path.startsWith(group.prefix))?.title ?? FALLBACK_GROUP
  );
}

/** What the scope column says for a route that requires none. */
function scopeCell(route: ApiRoute): string {
  if (route.scope) return `\`${route.scope}\``;
  return route.isPublic ? "none — public" : "any valid token";
}

function inputCell(route: ApiRoute): string {
  if (!route.input) return "—";
  return route.input.source;
}

/**
 * The reference page, generated from the same array that mounts the routes.
 *
 * Hand-written route tables drift more slowly than hand-written specs and
 * still drift — a path renamed in code and not in prose is a documented lie
 * that nobody notices until an integrator files it as a bug.
 */
export function referenceMarkdown(): string {
  const rows: string[] = [];
  for (const title of [...GROUPS.map((group) => group.title), FALLBACK_GROUP]) {
    const routes = API_ROUTES.filter((route) => groupOf(route) === title);
    if (routes.length === 0) continue;
    rows.push(`## ${title}\n`);
    rows.push("| Method | Path | Scope | Parameters | What it does |");
    rows.push("| --- | --- | --- | --- | --- |");
    for (const route of routes) {
      rows.push(
        `| \`${route.method.toUpperCase()}\` | \`${route.path}\` | ${scopeCell(route)} | ${inputCell(route)} | ${route.summary} |`,
      );
    }
    rows.push("");
  }

  return [
    "---",
    "sidebar_position: 5",
    "description: Every REST endpoint under /api/v1, the scope it requires, and where its parameters go.",
    "---",

    "",
    "{/* Generated by packages/server/src/api/v1/emit-openapi.ts — do not edit by hand. */}",
    "",
    "# API reference",
    "",
    "Every route below is mounted from one array, `API_ROUTES` in",
    "`packages/server/src/api/v1/routes-table.ts`, and this page and",
    "[the OpenAPI document](pathname:///openapi.json) are both generated from it. A route",
    "cannot exist here and not in the server, or in the server and not here.",
    "",
    "All paths are relative to `https://api.tracktime.trebeljahr.com/api/v1`. Every route",
    "but `/openapi.json` needs `Authorization: Bearer tt_…`. **Parameters** says where a",
    "route's input goes: `query` for a GET filter, `body` for JSON, `path` for the id in",
    "the URL. Full field-level shapes live in the OpenAPI document.",
    "",
    ...rows,
    "## The document itself",
    "",
    "- [`openapi.json`](pathname:///openapi.json) — the committed copy this site serves.",
    "- `GET /api/v1/openapi.json` — the live one, unauthenticated, generated per request",
    "  from the running server's own route table. Point a client generator at it.",
    "",
  ].join("\n");
}

export function emitReferencePage(target = REFERENCE_MD_PATH): string {
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, referenceMarkdown(), "utf8");
  return target;
}

// `import.meta.main` is not available on every Node this repo supports, so the
// entry check compares argv the way the other scripts here do. Both extensions,
// because this runs under tsx in development and as compiled JS in a container.
if (/emit-openapi\.(ts|js)$/.test(process.argv[1] ?? "")) {
  console.log(`[openapi] wrote ${emitOpenApiDocument()}`);
  console.log(`[openapi] wrote ${emitReferencePage()}`);
}
